export const products = [
  {
    id: 5,
    title: "Interruptor Siemens Q215 2P 15A",
    description: "Circuit breaker 2 poles 15 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q215 de 2 polos, 15 amperios, 120 voltios. DiseÃ±ado para protecciÃ³n residencial y comercial ligera.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/Q215-2.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/Q215-2.jpg"],
    price: 313.00,
    category: "interruptores-2p",
  },
  {
    id: 6,
    title: "Interruptor Siemens Q220 2P 20A",
    description: "Circuit breaker 2 poles 20 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q220 de 2 polos, 20 amperios, 120 voltios. Capacidad de ruptura 10kA con enchufable.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/q220-4.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/q220-4.jpg"],
    price: 313.00,
    category: "interruptores-2p",
  },
  {
    id: 7,
    title: "Interruptor Siemens Q230 2P 30A",
    description: "Circuit breaker 2 poles 30 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q230 de 2 polos, 30 amperios, 120 voltios. ProtecciÃ³n para cargas medianas con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/q230-1-200x200-1.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/q230-1-200x200-1.webp"],
    price: 313.00,
    category: "interruptores-2p",
  },
  {
    id: 8,
    title: "Interruptor Siemens Q240 2P 40A",
    description: "Circuit breaker 2 poles 40 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q240 de 2 polos, 40 amperios, 120 voltios. Enchufable 10kA para aplicaciones comerciales.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/q2402.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/q2402.jpg"],
    price: 313.00,
    category: "interruptores-2p",
  },
  {
    id: 9,
    title: "Interruptor Siemens Q250 2P 50A",
    description: "Circuit breaker 2 poles 50 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q250 de 2 polos, 50 amperios, 120 voltios. ProtecciÃ³n industrial con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/Q250-scaled-1.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/Q250-scaled-1.webp"],
    price: 313.00,
    category: "interruptores-2p",
  },
  {
    id: 10,
    title: "Interruptor Siemens Q260 2P 60A",
    description: "Circuit breaker 2 poles 60 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q260 de 2 polos, 60 amperios, 120 voltios. Enchufable 10kA para cargas pesadas.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/Q260-4-768x768.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/Q260-4-768x768.jpg"],
    price: 371.00,
    category: "interruptores-2p",
  },
  {
    id: 11,
    title: "Interruptor Siemens Q270 2P 70A",
    description: "Circuit breaker 2 poles 70 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q270 de 2 polos, 70 amperios, 120 voltios. Capacidad de ruptura 10kA para aplicaciones industriales.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/q270-3.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/q270-3.webp"],
    price: 557.00,
    category: "interruptores-2p",
  },
  {
    id: 12,
    title: "Interruptor Siemens Q2100 2P 100A",
    description: "Circuit breaker 2 poles 100 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q2100 de 2 polos, 100 amperios, 120 voltios. ProtecciÃ³n industrial pesada con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/Q2100-1.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/Q2100-1.jpg"],
    price: 592.00,
    category: "interruptores-2p",
  },
  {
    id: 13,
    title: "Interruptor QO 2P 10A Enchufable",
    description: "Thermal magnetic switch QO 2P 10 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 10 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO210_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO210_DA19_369.jpg"],
    price: 399.00,
    category: "interruptores-2p",
  },
  {
    id: 14,
    title: "Interruptor QO 2P 15A Enchufable",
    description: "Thermal magnetic switch QO 2P 15 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 15 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO215_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO215_DA19_369.jpg"],
    price: 399.00,
    category: "interruptores-2p",
  },
  {
    id: 15,
    title: "Interruptor QO 2P 20A Enchufable",
    description: "Thermal magnetic switch QO 2P 20 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 20 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/sd-qo220.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/sd-qo220.jpg"],
    price: 399.00,
    category: "interruptores-2p",
  },
  {
    id: 16,
    title: "Interruptor QO 2P 30A Enchufable",
    description: "Thermal magnetic switch QO 2P 30 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 30 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO230_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO230_DA19_369.jpg"],
    price: 420.00,
    category: "interruptores-2p",
  },
  {
    id: 17,
    title: "Interruptor QO 2P 40A Enchufable",
    description: "Thermal magnetic switch QO 2P 40 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 40 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO240_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO240_DA19_369.jpg"],
    price: 420.00,
    category: "interruptores-2p",
  },
  {
    id: 18,
    title: "Interruptor QO 2P 50A Enchufable",
    description: "Thermal magnetic switch QO 2P 50 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 50 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO250_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO250_DA19_369.jpg"],
    price: 445.00,
    category: "interruptores-2p",
  },
  {
    id: 19,
    title: "Interruptor QO 2P 60A Enchufable",
    description: "Thermal magnetic switch QO 2P 60 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 60 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO260_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO260_DA19_369.jpg"],
    price: 475.00,
    category: "interruptores-2p",
  },
  {
    id: 20,
    title: "Interruptor QO 2P 70A Enchufable",
    description: "Thermal magnetic switch QO 2P 70 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 70 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO270_DA22_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO270_DA22_369.jpg"],
    price: 515.00,
    category: "interruptores-2p",
  },
  {
    id: 21,
    title: "Interruptor QO 2P 100A Enchufable",
    description: "Thermal magnetic switch QO 2P 100 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 2 polos, 100 amperios, enchufable, capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/QO2100_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/QO2100_DA19_369.jpg"],
    price: 645.00,
    category: "interruptores-2p",
  },
  {
    id: 22,
    title: "Interruptor D215 2P 15A",
    description: "Breaker D215 2 poles 15 amp",
    details: "Interruptor de 2 polos, 15 amperios. Modelo D215 para protecciÃ³n residencial.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D215EE-370x370.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D215EE-370x370.webp"],
    price: 278.00,
    category: "interruptores-2p",
  },
  {
    id: 23,
    title: "Interruptor D220 2P 20A",
    description: "Breaker D220 2 poles 20 amp",
    details: "Interruptor de 2 polos, 20 amperios. Modelo D220 para protecciÃ³n residencial y comercial.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D220EE-768x768.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D220EE-768x768.webp"],
    price: 278.00,
    category: "interruptores-2p",
  },
  {
    id: 24,
    title: "Interruptor D230 2P 30A",
    description: "Breaker D230 2 poles 30 amp",
    details: "Interruptor de 2 polos, 30 amperios. Modelo D230 para cargas medianas.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D230EE.webp",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D230EE.webp"],
    price: 289.00,
    category: "interruptores-2p",
  },
  {
    id: 25,
    title: "Interruptor D240 2P 40A",
    description: "Breaker D240 2 poles 40 amp",
    details: "Interruptor de 2 polos, 40 amperios. Modelo D240 para cargas comerciales.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D240EE.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D240EE.jpg"],
    price: 298.00,
    category: "interruptores-2p",
  },
  {
    id: 26,
    title: "Interruptor D250 2P 50A",
    description: "Breaker D250 2 poles 50 amp",
    details: "Interruptor de 2 polos, 50 amperios. Modelo D250 para cargas pesadas.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D250EE.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D250EE.jpg"],
    price: 315.00,
    category: "interruptores-2p",
  },
  {
    id: 27,
    title: "Interruptor D260 2P 60A",
    description: "Breaker D260 2 poles 60 amp",
    details: "Interruptor de 2 polos, 60 amperios. Modelo D260 para protecciÃ³n industrial.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/D260EE.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/D260EE.jpg"],
    price: 335.00,
    category: "interruptores-2p",
  },
  {
    id: 28,
    title: "Interruptor Siemens Q310 3P 10A",
    description: "Circuit breaker 3 poles 10 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q310 de 3 polos, 10 amperios, 120 voltios. DiseÃ±ado para protecciÃ³n residencial y comercial ligera.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg"],
    price: 1102.00,
    category: "interruptores-3p",
  },
  {
    id: 29,
    title: "Interruptor Siemens Q315 3P 15A",
    description: "Circuit breaker 3 poles 15 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q315 de 3 polos, 15 amperios, 120 voltios. Capacidad de ruptura 10kA con enchufable.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO315_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO315_DA19_369.jpg"],
    price: 1102.00,
    category: "interruptores-3p",
  },
  {
    id: 30,
    title: "Interruptor Siemens Q320 3P 20A",
    description: "Circuit breaker 3 poles 20 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q320 de 3 polos, 20 amperios, 120 voltios. ProtecciÃ³n para cargas medianas con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO320_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO320_DA19_369.jpg"],
    price: 1102.00,
    category: "interruptores-3p",
  },
  {
    id: 31,
    title: "Interruptor Siemens Q330 3P 30A",
    description: "Circuit breaker 3 poles 30 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q330 de 3 polos, 30 amperios, 120 voltios. Enchufable 10kA para aplicaciones comerciales.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO330_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO330_DA19_369.jpg"],
    price: 1102.00,
    category: "interruptores-3p",
  },
  {
    id: 32,
    title: "Interruptor Siemens Q340 3P 40A",
    description: "Circuit breaker 3 poles 40 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q340 de 3 polos, 40 amperios, 120 voltios. ProtecciÃ³n industrial con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO340_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO340_DA19_369.jpg"],
    price: 1102.00,
    category: "interruptores-3p",
  },
  {
    id: 33,
    title: "Interruptor Siemens Q350 3P 50A",
    description: "Circuit breaker 3 poles 50 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q350 de 3 polos, 50 amperios, 120 voltios. Enchufable 10kA para cargas pesadas.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO350-370x370.webp",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO350-370x370.webp"],
    price: 1125.00,
    category: "interruptores-3p",
  },
  {
    id: 34,
    title: "Interruptor Siemens Q360 3P 60A",
    description: "Circuit breaker 3 poles 60 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q360 de 3 polos, 60 amperios, 120 voltios. Capacidad de ruptura 10kA para aplicaciones industriales.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO360_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO360_DA19_369.jpg"],
    price: 1566.00,
    category: "interruptores-3p",
  },
  {
    id: 35,
    title: "Interruptor Siemens Q370 3P 70A",
    description: "Circuit breaker 3 poles 70 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q370 de 3 polos, 70 amperios, 120 voltios. ProtecciÃ³n industrial pesada con capacidad de ruptura 10kA.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO370_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO370_DA19_369.jpg"],
    price: 1566.00,
    category: "interruptores-3p",
  },
  {
    id: 36,
    title: "Interruptor QO 3P 10A Enchufable",
    description: "Thermal magnetic switch QO 3P 10 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 10 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n residencial y comercial.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/4401731063.png",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/4401731063.png"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 37,
    title: "Interruptor QO 3P 15A Enchufable",
    description: "Thermal magnetic switch QO 3P 15 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 15 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n para cargas medianas.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/Capturadepantalla2021-03-12ala_s_08.40.20_430x421-300x300.png",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/Capturadepantalla2021-03-12ala_s_08.40.20_430x421-300x300.png"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 38,
    title: "Interruptor QO 3P 20A Enchufable",
    description: "Thermal magnetic switch QO 3P 20 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 20 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n comercial e industrial.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 39,
    title: "Interruptor QO 3P 30A Enchufable",
    description: "Thermal magnetic switch QO 3P 30 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 30 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n para cargas pesadas.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q330-2.webp",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q330-2.webp"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 40,
    title: "Interruptor QO 3P 40A Enchufable",
    description: "Thermal magnetic switch QO 3P 40 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 40 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n industrial.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO3100_DA19_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO3100_DA19_369.jpg"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 41,
    title: "Interruptor QO 3P 50A Enchufable",
    description: "Thermal magnetic switch QO 3P 50 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 50 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n industrial pesada.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg"],
    price: 1624.00,
    category: "interruptores-3p",
  },
  {
    id: 42,
    title: "Interruptor QO 3P 100A Enchufable",
    description: "Thermal magnetic switch QO 3P 100 amp 10kA 120/240V",
    details: "Interruptor termomagnÃ©tico QO de 3 polos, 100 amperios, enchufable, 10kA, 120/240 voltios. ProtecciÃ³n industrial mÃ¡xima.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/QO310_DA_369.jpg"],
    price: 2552.00,
    category: "interruptores-3p",
  },
  {
    id: 43,
    title: "Interruptor Siemens Q115 1P 15A",
    description: "Single pole circuit breaker 15 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q115 de 1 polo, 15 amperios, 120 voltios. ProtecciÃ³n residencial estÃ¡ndar.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q115, 15 Amp, 1 Polo, 120 Voltios.jpg",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q115, 15 Amp, 1 Polo, 120 Voltios.jpg"],
    price: 128.00,
    category: "interruptores-1p",
  },
  {
    id: 44,
    title: "Interruptor Siemens Q120 1P 20A",
    description: "Single pole circuit breaker 20 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q120 de 1 polo, 20 amperios, 120 voltios. DiseÃ±o compacto para tableros residenciales.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q120, 20 Amp, 1 Polo, 120 Voltios.jpg",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q120, 20 Amp, 1 Polo, 120 Voltios.jpg"],
    price: 128.00,
    category: "interruptores-1p",
  },
  {
    id: 45,
    title: "Interruptor Siemens Q130 1P 20A",
    description: "Single pole circuit breaker 20 amp 120 volts",
    details: "Interruptor termomagnÃ©tico Siemens Q130 de 1 polo, 20 amperios, 120 voltios. ProtecciÃ³n mejorada con capacidad de ruptura.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q130, 20 Amp, 1 Polo, 120 Voltios.webp",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/128.00 Interruptor Siemens Q130, 20 Amp, 1 Polo, 120 Voltios.webp"],
    price: 128.00,
    category: "interruptores-1p",
  },
  {
    id: 46,
    title: "Interruptor QO 1P 15A Enchufable",
    description: "Single pole QO breaker 15 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 15 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 15 A. ENCHUFABLE 10kA 120 240V.jpg",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 15 A. ENCHUFABLE 10kA 120 240V.jpg"],
    price: 151.00,
    category: "interruptores-1p",
  },
  {
    id: 47,
    title: "Interruptor QO 1P 20A Enchufable",
    description: "Single pole QO breaker 20 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 20 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 20 A. ENCHUFABLE 10kA 120 240V.jpg",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 20 A. ENCHUFABLE 10kA 120 240V.jpg"],
    price: 151.00,
    category: "interruptores-1p",
  },
  {
    id: 48,
    title: "Interruptor QO 1P 30A Enchufable",
    description: "Single pole QO breaker 30 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 30 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 30 A. ENCHUFABLE 10kA 120 240V.webp",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 30 A. ENCHUFABLE 10kA 120 240V.webp"],
    price: 151.00,
    category: "interruptores-1p",
  },
  {
    id: 49,
    title: "Interruptor QO 1P 40A Enchufable",
    description: "Single pole QO breaker 40 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 40 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 40 A. ENCHUFABLE 10kA 120 240V.webp",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/151.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 40 A. ENCHUFABLE 10kA 120 240V.webp"],
    price: 151.00,
    category: "interruptores-1p",
  },
  {
    id: 50,
    title: "Interruptor QO 1P 50A Enchufable",
    description: "Single pole QO breaker 50 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 50 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/174.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 50 A. ENCHUFABLE 10kA 120 240V.webp",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/174.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 50 A. ENCHUFABLE 10kA 120 240V.webp"],
    price: 174.00,
    category: "interruptores-1p",
  },
  {
    id: 51,
    title: "Interruptor QO 1P 60A Enchufable",
    description: "Single pole QO breaker 60 amp 10kA",
    details: "Interruptor termomagnÃ©tico QO de 1 polo, 60 amperios, enchufable, capacidad de ruptura 10kA, 120/240 voltios.",
    image: "/IMGPRODUCTS/Interruptores _1_polo/219.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 60 A. ENCHUFABLE 10kA 120 240V.webp",
    images: ["/IMGPRODUCTS/Interruptores _1_polo/219.00 INTERRUPTOR TERMOMAGNETICO QO 1P. 60 A. ENCHUFABLE 10kA 120 240V.webp"],
    price: 219.00,
    category: "interruptores-1p",
  },
  {
    id: 52,
    title: "Centro de Carga QD Siemens 2 Espacios Empotrar",
    description: "QD load center 2 spaces flush mounted electrical distribution",
    details: "Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens, diseÃ±o empotrado. ProtecciÃ³n y distribuciÃ³n de circuitos.",
    image: "/IMGPRODUCTS/Centro_de_carga/231.00 Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens Empotrar.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/231.00 Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens Empotrar.webp"],
    price: 231.00,
    category: "centro-carga",
  },
  {
    id: 53,
    title: "Centro de Carga QD Siemens 2 Espacios Sobreponer",
    description: "QD load center 2 spaces surface mounted electrical distribution",
    details: "Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens, diseÃ±o sobrepuesto. InstalaciÃ³n flexible y accesible.",
    image: "/IMGPRODUCTS/Centro_de_carga/231.00 Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens Sobrepone}.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/231.00 Centro de carga QD metÃ¡lico de 2 espacios para distribuciÃ³n elÃ©ctrica Siemens Sobrepone}.webp"],
    price: 231.00,
    category: "centro-carga",
  },
  {
    id: 54,
    title: "Centro de Carga QT QP 2-4 Polos Empotrar",
    description: "QT QP load center 2-4 poles 2 phase 3 wires flush mounted",
    details: "Centro de carga QT QP de 2-4 polos, 2 fases, 3 hilos, diseÃ±o empotrado. DistribuciÃ³n versÃ¡til para diferentes aplicaciones.",
    image: "/IMGPRODUCTS/Centro_de_carga/231.00 centro de carga qt qp 2-4 polos ml 2 fases 3 hilos empotrar.png",
    images: ["/IMGPRODUCTS/Centro_de_carga/231.00 centro de carga qt qp 2-4 polos ml 2 fases 3 hilos empotrar.png"],
    price: 231.00,
    category: "centro-carga",
  },
  {
    id: 55,
    title: "Centro de Carga QT QP 2-4 Polos Sobreponer",
    description: "QT QP load center 2-4 poles 2 phase 3 wires surface mounted",
    details: "Centro de carga QT QP de 2-4 polos, 2 fases, 3 hilos, diseÃ±o sobrepuesto. InstalaciÃ³n flexible y moderna.",
    image: "/IMGPRODUCTS/Centro_de_carga/231.00 centro de carga qt qp 2-4 polos ml 2 fases 3 hilos Sobreponer.png",
    images: ["/IMGPRODUCTS/Centro_de_carga/231.00 centro de carga qt qp 2-4 polos ml 2 fases 3 hilos Sobreponer.png"],
    price: 231.00,
    category: "centro-carga",
  },
  {
    id: 56,
    title: "Centro de Carga MonofÃ¡sico 12 Circuitos Empotrar",
    description: "Load center single phase 12 circuits flush mounted",
    details: "Centro de carga monofÃ¡sico de 12 circuitos, diseÃ±o empotrado. DistribuciÃ³n completa para viviendas y locales pequeÃ±os.",
    image: "/IMGPRODUCTS/Centro_de_carga/2610.00 Centro de carga empotrar monofÃ¡sico 12 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/2610.00 Centro de carga empotrar monofÃ¡sico 12 circuitos.jpg"],
    price: 2610.00,
    category: "centro-carga",
  },
  {
    id: 57,
    title: "Centro de Carga MonofÃ¡sico 12 Circuitos Sobreponer",
    description: "Load center single phase 12 circuits surface mounted",
    details: "Centro de carga monofÃ¡sico de 12 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n rÃ¡pida y fÃ¡cil acceso a protecciones.",
    image: "/IMGPRODUCTS/Centro_de_carga/2610.00 Centro de carga sobreponer monofÃ¡sico 12 circuitos.png",
    images: ["/IMGPRODUCTS/Centro_de_carga/2610.00 Centro de carga sobreponer monofÃ¡sico 12 circuitos.png"],
    price: 2610.00,
    category: "centro-carga",
  },
  {
    id: 58,
    title: "Centro de Carga MonofÃ¡sico 24 Circuitos Empotrar",
    description: "Load center single phase 24 circuits flush mounted",
    details: "Centro de carga monofÃ¡sico de 24 circuitos, diseÃ±o empotrado. DistribuciÃ³n amplia para locales comerciales.",
    image: "/IMGPRODUCTS/Centro_de_carga/3747.00 Centro de carga empotrar monofÃ¡sico 24 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3747.00 Centro de carga empotrar monofÃ¡sico 24 circuitos.jpg"],
    price: 3747.00,
    category: "centro-carga",
  },
  {
    id: 59,
    title: "Centro de Carga MonofÃ¡sico 24 Circuitos Sobreponer",
    description: "Load center single phase 24 circuits surface mounted",
    details: "Centro de carga monofÃ¡sico de 24 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n flexible para ampliaciones de sistemas.",
    image: "/IMGPRODUCTS/Centro_de_carga/3747.00 Centro de carga sobreponer monofÃ¡sico 24 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3747.00 Centro de carga sobreponer monofÃ¡sico 24 circuitos.jpg"],
    price: 3747.00,
    category: "centro-carga",
  },
  {
    id: 60,
    title: "Centro de Carga QP QT 4 Polos 8 Circuitos Empotrar",
    description: "QP QT load center 4 poles 8 circuits flush mounted",
    details: "Centro de carga QP QT de 4 polos hasta 8 circuitos, diseÃ±o empotrado. ProtecciÃ³n para aplicaciones trifÃ¡sicas.",
    image: "/IMGPRODUCTS/Centro_de_carga/383.00 Centro de carga QP QT 4 polos hasta 8 circuitos empotrar.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/383.00 Centro de carga QP QT 4 polos hasta 8 circuitos empotrar.webp"],
    price: 383.00,
    category: "centro-carga",
  },
  {
    id: 61,
    title: "Centro de Carga QP QT 4 Polos 8 Circuitos Sobreponer",
    description: "QP QT load center 4 poles 8 circuits surface mounted",
    details: "Centro de carga QP QT de 4 polos hasta 8 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n versÃ¡til para sistemas trifÃ¡sicos.",
    image: "/IMGPRODUCTS/Centro_de_carga/383.00 Centro de carga QP QT 4 polos hasta 8 circuitos sobreponer.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/383.00 Centro de carga QP QT 4 polos hasta 8 circuitos sobreponer.webp"],
    price: 383.00,
    category: "centro-carga",
  },
  {
    id: 62,
    title: "Centro de Carga MonofÃ¡sico 20 Circuitos Empotrar",
    description: "Load center single phase 20 circuits flush mounted",
    details: "Centro de carga monofÃ¡sico de 20 circuitos, diseÃ±o empotrado. DistribuciÃ³n Ã³ptima para medianos comercios.",
    image: "/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga empotrar monofÃ¡sico 20 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga empotrar monofÃ¡sico 20 circuitos.jpg"],
    price: 3944.00,
    category: "centro-carga",
  },
  {
    id: 63,
    title: "Centro de Carga TrifÃ¡sico 12 Circuitos Empotrar",
    description: "Load center three phase 12 circuits flush mounted",
    details: "Centro de carga trifÃ¡sico de 12 circuitos, diseÃ±o empotrado. ProtecciÃ³n completa para aplicaciones industriales.",
    image: "/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga empotrar trifÃ¡sico 12 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga empotrar trifÃ¡sico 12 circuitos.jpg"],
    price: 3944.00,
    category: "centro-carga",
  },
  {
    id: 64,
    title: "Centro de Carga MonofÃ¡sico 20 Circuitos Sobreponer",
    description: "Load center single phase 20 circuits surface mounted",
    details: "Centro de carga monofÃ¡sico de 20 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n rÃ¡pida para ampliaciones comerciales.",
    image: "/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga sobreponer monofÃ¡sico 20 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga sobreponer monofÃ¡sico 20 circuitos.jpg"],
    price: 3944.00,
    category: "centro-carga",
  },
  {
    id: 65,
    title: "Centro de Carga TrifÃ¡sico 12 Circuitos Sobreponer",
    description: "Load center three phase 12 circuits surface mounted",
    details: "Centro de carga trifÃ¡sico de 12 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n flexible para sistemas trifÃ¡sicos existentes.",
    image: "/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga sobreponer trifÃ¡sico 12 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/3944.00 Centro de carga sobreponer trifÃ¡sico 12 circuitos.jpg"],
    price: 3944.00,
    category: "centro-carga",
  },
  {
    id: 66,
    title: "Centro de Carga 4 Espacios QP Siemens T04ML2125F Empotrar",
    description: "QP load center 4 spaces Siemens T04ML2125F flush mounted",
    details: "Centro de carga 4 espacios QP empotrar Siemens T04ML2125F. DistribuciÃ³n moderna para aplicaciones comerciales.",
    image: "/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga 4 espacios QP empotrar SIEMENS T04ML2125F empotrar.png",
    images: ["/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga 4 espacios QP empotrar SIEMENS T04ML2125F empotrar.png"],
    price: 430.00,
    category: "centro-carga",
  },
  {
    id: 67,
    title: "Centro de Carga 4 Espacios QP Siemens T04ML2125F Sobreponer",
    description: "QP load center 4 spaces Siemens T04ML2125F surface mounted",
    details: "Centro de carga 4 espacios QP sobreponer Siemens T04ML2125F. InstalaciÃ³n versÃ¡til y accesible.",
    image: "/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga 4 espacios QP empotrar SIEMENS T04ML2125F sobreponer.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga 4 espacios QP empotrar SIEMENS T04ML2125F sobreponer.webp"],
    price: 430.00,
    category: "centro-carga",
  },
  {
    id: 68,
    title: "Centro de Carga QD Siemens 4 Espacios Empotrar",
    description: "QD load center 4 spaces flush mounted electrical distribution",
    details: "Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens, diseÃ±o empotrado.",
    image: "/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens Empotrar.png",
    images: ["/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens Empotrar.png"],
    price: 430.00,
    category: "centro-carga",
  },
  {
    id: 69,
    title: "Centro de Carga QD Siemens 4 Espacios Sobreponer",
    description: "QD load center 4 spaces surface mounted electrical distribution",
    details: "Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens, diseÃ±o sobrepuesto.",
    image: "/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens Sobreponer.webp",
    images: ["/IMGPRODUCTS/Centro_de_carga/430.00 Centro de carga QD metÃ¡lico de 4 espacios para distribuciÃ³n elÃ©ctrica Siemens Sobreponer.webp"],
    price: 430.00,
    category: "centro-carga",
  },
  {
    id: 70,
    title: "Centro de Carga TrifÃ¡sico 20 Circuitos Empotrar",
    description: "Load center three phase 20 circuits flush mounted",
    details: "Centro de carga trifÃ¡sico de 20 circuitos, diseÃ±o empotrado. DistribuciÃ³n industrial completa con capacidad expandida.",
    image: "/IMGPRODUCTS/Centro_de_carga/6000.00 - 5568.00 Centro de carga empotrar trifÃ¡sico 20 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/6000.00 - 5568.00 Centro de carga empotrar trifÃ¡sico 20 circuitos.jpg"],
    price: 5568.00,
    category: "centro-carga",
  },
  {
    id: 71,
    title: "Centro de Carga TrifÃ¡sico 20 Circuitos Sobreponer",
    description: "Load center three phase 20 circuits surface mounted",
    details: "Centro de carga trifÃ¡sico de 20 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n flexible para ampliaciones industriales.",
    image: "/IMGPRODUCTS/Centro_de_carga/6000.00 Centro de carga sobreponer trifÃ¡sico 20 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/6000.00 Centro de carga sobreponer trifÃ¡sico 20 circuitos.jpg"],
    price: 6000.00,
    category: "centro-carga",
  },
  {
    id: 72,
    title: "Centro de Carga MonofÃ¡sico 30 Circuitos Empotrar",
    description: "Load center single phase 30 circuits flush mounted",
    details: "Centro de carga monofÃ¡sico de 30 circuitos, diseÃ±o empotrado. DistribuciÃ³n mÃ¡xima para grandes comercios.",
    image: "/IMGPRODUCTS/Centro_de_carga/6148.00 Centro de carga empotrar monofÃ¡sico 30 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/6148.00 Centro de carga empotrar monofÃ¡sico 30 circuitos.jpg"],
    price: 6148.00,
    category: "centro-carga",
  },
  {
    id: 73,
    title: "Centro de Carga MonofÃ¡sico 30 Circuitos Sobreponer",
    description: "Load center single phase 30 circuits surface mounted",
    details: "Centro de carga monofÃ¡sico de 30 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n versÃ¡til para ampliaciones grandes.",
    image: "/IMGPRODUCTS/Centro_de_carga/6148.00 Centro de carga sobreponer monofÃ¡sico 30 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/6148.00 Centro de carga sobreponer monofÃ¡sico 30 circuitos.jpg"],
    price: 6148.00,
    category: "centro-carga",
  },
  {
    id: 74,
    title: "Centro de Carga Square D 100A 1 Fase 6 Polos Empotrar",
    description: "Square D load center 100A single phase 6 poles NEMA1 flush mounted",
    details: "Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, diseÃ±o empotrado. ProtecciÃ³n industrial robusta.",
    image: "/IMGPRODUCTS/Centro_de_carga/754.00 Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, para empotrar.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/754.00 Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, para empotrar.jpg"],
    price: 754.00,
    category: "centro-carga",
  },
  {
    id: 75,
    title: "Centro de Carga Square D 100A 1 Fase 6 Polos Sobreponer",
    description: "Square D load center 100A single phase 6 poles NEMA1 surface mounted",
    details: "Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, diseÃ±o sobrepuesto. InstalaciÃ³n flexible.",
    image: "/IMGPRODUCTS/Centro_de_carga/754.00 Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, para sobre poner.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/754.00 Centro de carga de zapatas Square D de 100A, 1 fase, 6 polos, NEMA1, para sobre poner.jpg"],
    price: 754.00,
    category: "centro-carga",
  },
  {
    id: 76,
    title: "Centro de Carga TrifÃ¡sico 30 Circuitos Empotrar",
    description: "Load center three phase 30 circuits flush mounted",
    details: "Centro de carga trifÃ¡sico de 30 circuitos, diseÃ±o empotrado. DistribuciÃ³n industrial mÃ¡xima con capacidad completa.",
    image: "/IMGPRODUCTS/Centro_de_carga/7888.00 Centro de carga empotrar trifÃ¡sico 30 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/7888.00 Centro de carga empotrar trifÃ¡sico 30 circuitos.jpg"],
    price: 7888.00,
    category: "centro-carga",
  },
  {
    id: 77,
    title: "Centro de Carga TrifÃ¡sico 30 Circuitos Sobreponer",
    description: "Load center three phase 30 circuits surface mounted",
    details: "Centro de carga trifÃ¡sico de 30 circuitos, diseÃ±o sobrepuesto. InstalaciÃ³n flexible para grandes sistemas industriales.",
    image: "/IMGPRODUCTS/Centro_de_carga/7888.00 Centro de carga sobreponer trifÃ¡sico 30 circuitos.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/7888.00 Centro de carga sobreponer trifÃ¡sico 30 circuitos.jpg"],
    price: 7888.00,
    category: "centro-carga",
  },
  {
    id: 78,
    title: "Centro de Carga Square D 100A 1 Fase 8 Polos Empotrar",
    description: "Square D load center 100A single phase 8 poles NEMA1 flush mounted",
    details: "Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, diseÃ±o empotrado. MÃ¡xima capacidad de circuitos.",
    image: "/IMGPRODUCTS/Centro_de_carga/986.00 Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, para empotrar.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/986.00 Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, para empotrar.jpg"],
    price: 986.00,
    category: "centro-carga",
  },
  {
    id: 79,
    title: "Centro de Carga Square D 100A 1 Fase 8 Polos Sobreponer",
    description: "Square D load center 100A single phase 8 poles NEMA1 surface mounted",
    details: "Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, diseÃ±o sobrepuesto. InstalaciÃ³n versÃ¡til con mÃ¡xima capacidad.",
    image: "/IMGPRODUCTS/Centro_de_carga/986.00 Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, para sobre poner.jpg",
    images: ["/IMGPRODUCTS/Centro_de_carga/986.00 Centro de carga de zapatas Square D de 100A, 1 fase, 8 polos, NEMA1, para sobre poner.jpg"],
    price: 986.00,
    category: "centro-carga",
  },
];


